name: Test
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Check Gradle
        run: |
          gradle -q javaToolchains
      - name: List JAVA* env variables
        run: |
          printenv | grep JAVA
      - name: Run verifyPluginConfiguration
        run: |
          gradle verifyPluginConfiguration
